# Configurações do Site
title: InvestSavy
description: Portal líder em notícias financeiras e análises de mercado
baseurl: '/InvestSavy' # Mantenha vazio para desenvolvimento local
url: 'https://lcodebase.github.io/InvestSavy/'

# Configurações de Build
markdown: kramdown
permalink: /:categories/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Configurações de Coleções
collections:
  posts:
    output: true
    permalink: /:categories/:title/
  destaques:
    output: true
    permalink: /destaques/:title/
  mercados:
    output: true
    permalink: /mercados/:title/
  economia:
    output: true
    permalink: /economia/:title/
  politica:
    output: true
    permalink: /politica/:title/
  tecnologia:
    output: true
    permalink: /tecnologia/:title/
  energia:
    output: true
    permalink: /energia/:title/

# Configurações de Layout
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      author: 'Equipe InvestSavy'
      comments: true
  - scope:
      path: ''
      type: 'destaques'
    values:
      layout: 'post'
      author: 'Equipe InvestSavy'
  - scope:
      path: ''
      type: 'mercados'
    values:
      layout: 'post'
      author: 'Equipe InvestSavy'
  - scope:
      path: ''
      type: 'economia'
    values:
      layout: 'post'
      author: 'Equipe InvestSavy'
  - scope:
      path: ''
      type: 'politica'
    values:
      layout: 'post'
      author: 'Equipe InvestSavy'
  - scope:
      path: ''
      type: 'tecnologia'
    values:
      layout: 'post'
      author: 'Equipe InvestSavy'
  - scope:
      path: ''
      type: 'energia'
    values:
      layout: 'post'
      author: 'Equipe InvestSavy'

# Configurações de Exclusão
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
  - LICENSE

# Configurações de SASS
sass:
  style: compressed

# Configurações de SEO
seo:
  title: InvestSavy - Portal de Notícias Financeiras
  description: Notícias financeiras, análises de mercado e cotações em tempo real
  keywords: investimentos, finanças, mercado, economia, bolsa de valores
  author: InvestSavy
  twitter:
    username: '@investsavy'
    card: summary_large_image

# Configurações de servidor
port: 4000
host: localhost
